### ISSUE TITLE
Wrong url for external scaler KEDA HTTP && KEDA External Scaler for Azure Cosmos DB.

### ISSUE THREAD

**Issue by Adarsh-verma-14** [kedacore/keda-docs#1021]
Links of external scalers (KEDA HTTP && KEDA External Scaler for Azure Cosmos DB) are not working on this page -https://keda.sh/docs/2.9/scalers/ 

### Expected Behavior
The links should direct to -
for KEDA  HTTP - https://github.com/kedacore/external-scalers/tree/main/artifacthub
for KEDA External Scaler for Azure Cosmos DB - https://github.com/kedacore/external-scalers/tree/main/artifacthub

### Actual Behavior
The links are directing here -
for KEDA HTTP - https://github.com/kedacore/external-scalers/artifacthub
for KEDA External Scaler for Azure Cosmos DB - https://github.com/kedacore/external-scalers/artifacthub

**Comment by Adarsh-verma-14** [comment]
@tomkerkhove  @JorTurFer 
Reason is that these external scalers's links are pulled the data form this url -https://artifacthub.io/api/v1/packages/search?offset=0&limit=20&facets=false&kind=8&deprecated=false&sort=relevance  and the output of this url is -
![Screenshot from 2022-12-21 14-56-09](https://user-images.githubusercontent.com/113962919/208870836-616a4043-86b5-4f2d-a67f-5b25bc29dc88.png)
so first we need to change url in its output.

**Comment by JorTurFer** [comment]
I have no idea about how artifact hub works, maybe @tomkerkhove knows it

**Comment by tomkerkhove** [comment]
@tegioz this might be a bug.

We are defining our external scalers in https://github.com/kedacore/external-scalers/tree/main which has a folder per official KEDA external scaler but the search results are not rendering valid URLs.

Can we configure these somewhere?

**Comment by tegioz** [comment]
Hi @tomkerkhove 👋

The repository url you see in the search API output represents the url as it was added to AH. That url is correct and it uses the [format expected by AH](https://artifacthub.io/docs/topics/repositories/keda-scalers/) so that it can be processed periodically.

It looks like what you need is a URL for each of the packages. There are a few ways you could get this done:

### Using AH packages urls

This is probably the easiest way, as you have everything you need from the search API output, but you'll need to build the urls on your end. The format would be:

`https://artifacthub.io/packages/keda-scaler/{REPO_NAME}/{PKG_NORMALIZED_NAME}`

And you can get both the **repo name** and the **package normalized name** from the output displayed above. The result would be a link like the one below:

<https://artifacthub.io/packages/keda-scaler/keda-official-external-scalers/keda-add-ons-http>

### Using links provided by the package provider

Another alternative would be to get some [extra information from AH for each of the packages](https://artifacthub.io/docs/api/#/Packages/getKedaScalerDetails), which will return all links provided by the package. If by convention you know all scalers will provide a source link, for example, you could rely on that and use that link.

This approach requires an extra API call per package, and it may not be as solid as in the end it will depend on something extra each package would need to provide, so I would recommend going with the first one.

Hope this helps 🙂

**Comment by tomkerkhove** [comment]
Definately helps, thanks! It looks like we should be using option 1 to avoid doing too many API calls.

Adding this to our doc improvement project for @chalin, @thisisobate and team.
