### ISSUE TITLE
We should document that we leverage multiple sources in the architecture docs

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda-docs#119]
We should document that we leverage multiple sources in the architecture docs.

Something similar to the following, but prettier.

Without:
![image](https://user-images.githubusercontent.com/4345663/76968604-7d995d80-6929-11ea-9d97-7db96af5c0c0.png)

With KEDA:
![image](https://user-images.githubusercontent.com/4345663/76968601-7bcf9a00-6929-11ea-8c80-ec590e6c63f0.png)

**Comment by so0k** [comment]
This is a great visualisation, the next question that pops in my head seeing this is: "why the need for ScaledObject CRD and not use HPA" I guess because KEDA is not an external metrics provider and is just the direct provider for it's own CRD (still not clear why this approach instead of the upstream one)

That might also help clarify why one would consider KEDA if you already have a central metrics store (DataDog / Prometheus) - KEDA is a more lightweight approach?

**Comment by tomkerkhove** [comment]
KEDA is an external metric provider for a variety of external systems, including Prometheus. We use ScaledObject CRD because we are building on top of HPA (not replacing) and provide additional features such as scale to 0.

KEDA scans for ScaledObjects and interprets the required triggers to monitor those systems and provide metrics for those so that the HPA will be created on the fly and scaled based on those metrics.

Prometheus / Datadog are external metric providers for just those systems, KEDA takes it a step further and supports 20+ systems.

**Comment by so0k** [comment]
well, DataDog external metrics provider "are for just those systems" - is kind of moot if you channel all your metrics through them... no? You don't need KEDA if you already scrape your job queue length into datadog or scrape microservice endpoints which give you business metrics which you may want to scale no, right?

**Comment by tomkerkhove** [comment]
If everything is in Datadog then you should be good to go, we provide multiple platforms so that you can use same approach for all; not implying we are doing a better job or so - Don't get me wrong!

You can use one or the other indeed!
