### ISSUE TITLE
Docs are not versioned

### ISSUE THREAD

**Issue by shaikatz** [kedacore/keda-docs#135]
Hi,

I've read through the docs about how to use AWS scalers, and added `identityOwner` just to find out that this feature was not relased yet.

It could be nice if there will be a version picker in the docs, to make sure the user understand he is reading the latest unreleased versioned docs.

**Comment by tomkerkhove** [comment]
_Moved issue to docs repo._

Fair request @shaikatz!

**Comment by tomkerkhove** [comment]
Any recommended approach for this @lucperkins other than version folders and duplicating it?

**Comment by zroubalik** [comment]
+1 we should prepare this for v2.0 release. As some documentation will be changed.

**Comment by tomkerkhove** [comment]
So let's do this right from the get go to save @lucperkins a lot of time:
- We'll version main docs
- We'll version per-scaler docs

**Comment by zroubalik** [comment]
thanks @lucperkins for doing this!

**Comment by lucperkins** [comment]
To be clear, this is not getting it right from the get-go and is not saving me time. This is a significant time expenditure that could have been saved had this been brought to my attention initially. In future projects, I'd strongly suggest choosing versioned vs. non-versioned as early as possible, as they require completely separate setups.

**Comment by tomkerkhove** [comment]
Our scalers are released with the core for now so a general version seems like the best approach imo.

Our concepts are going to change with v2.x since our specifications will change so those should be covered as well.

What I think is best is to have:
- `https://keda.sh/docs/concepts/` & `https://keda.sh/scalers/<scaler>/` --> Latest docs 
- `https://keda.sh/v1.4/docs/concepts/` & `https://keda.sh/v1.4/scalers/<scaler>/` --> Docs which are related to v1.4 and includes all pages

**Comment by lucperkins** [comment]
On second thought, could one of the maintainers provide a rationale for versioning? I get that there is an issue in this particular case, but are there indicators that many users will have problems like this? Will there be a significant number of users who are "stuck" on 1.4 after 2.0 is released? How different will the 2.0 docs be from the 1.4 docs?

I ask mostly because there doesn't seem to be much material that'd be a candidate for versioning. The concepts docs will remain the same across the versions, as will the FAQ. My same question goes for the scaler docs. Is there a known demand for versions beyond this issue?

**Comment by shaikatz** [comment]
The concept page also includes a list of scalers, architecture, CRD description.
Those things can definitely change between versions. 
I like @tomkerkhove proposal, which is standard in a lot of grown-up OSS projects.

**Comment by tomkerkhove** [comment]
@lucperkins Issue is that every new release we provide new features for our scalers as well so we just add them to the current docs for now; but if you are 2 versions behind that only confuses/frustrates people since they try the new feature but isn't around yet.

Going from v1.4 to v2.0 is just an example of changes that will happen to the concepts; but for minor version increments we can update deployment, new authentication provider or additional features, etc.

**Comment by lucperkins** [comment]
@tomkerkhove What's the current version of the scalers?

**Comment by tomkerkhove** [comment]
@lucperkins They are 1.4, same as the core

**Comment by tomkerkhove** [comment]
This is now done, thanks @lucperkins!
