### ISSUE TITLE
Provide dedicated page per authentication provider

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/keda-docs#711]
As our offering for trigger authentication is growing, so does [our list of supported authentication providers](https://keda.sh/docs/2.6/concepts/authentication/).

We would love to align our approach in this area with our [scaler conceptual documentation](https://keda.sh/docs/2.6/concepts/scaling-deployments/) and [dedicated scaler overview](https://keda.sh/docs/2.6/scalers/).

With this change, there should be a list of supported authentication providers with a link to a dedicated page showing when it was introduced and how to use it.

**Comment by tomkerkhove** [comment]
@chalin Is this something you can pick up as part of the rework?

**Comment by chalin** [comment]
@tomkerkhove - yes it can be. It would help if I knew the relative priority of issues -- see #727.

**Comment by tegioz** [comment]
Hi 👋

Maybe @cynthia-sg can help you with this 🙂

Could you please share some more details about how would you like to structure/split that page?

**Comment by tomkerkhove** [comment]
That would be nice, thank you!

Currently we have all the providers documented on https://keda.sh/docs/latest/concepts/authentication/ but we would like to align to our scaler model where the landing page shows all the available providers (similar to https://keda.sh/docs/latest/scalers/) with a dedicated page per provider (similar to https://keda.sh/docs/latest/scalers/apache-kafka/).

This would make it a lot easier for end-users to explore our authentication providers instead of using our current way-too-long page.

**Comment by cynthia-sg** [comment]
Hi there! 👋

I have been checking the issue and I was wondering if you had in mind something similar to this:

<img width="1711" alt="keda_providers_1" src="https://user-images.githubusercontent.com/1440981/182592733-64360d8b-ba29-4cbf-a4e3-be671a368827.png">

I have used the old buttons for linking with the provider information, but if you prefer we can use something similar to the card used now for scalers (it's be great if you can help with the info to show for providers).
￼
<img width="479" alt="ActiveMQ Artemis" src="https://user-images.githubusercontent.com/1440981/182592862-8edc9f69-5046-4797-8f55-72019b970cb5.png">
￼
<img width="1711" alt="keda_providers_2" src="https://user-images.githubusercontent.com/1440981/182592765-a9f2e8bb-7a73-40b5-8178-f81a24f21288.png">




Some questions: 
- Which version do I have to use for this? 2.7? 2.8?
- What information do you think that we can use for the 'Authentication Providers' page?


Note: In my last screenshoot, I have reduced the blank space between the section.hero and the content. Is the huge space intentional because it's affecting to all pages?

**Comment by tomkerkhove** [comment]
I love this!

We'll have to retro-actively sync the versions with when we shipped them but for me it's OK to start with 2.8 and duplicate them all the way back; I can clean it up later on.

The only concern I have is with the first screenshot where the information is still a bit hidden but we can improve that in a next PR IMO.

Thoughts @JorTurFer @zroubalik ?

**Comment by zroubalik** [comment]
Agree and I think that we don't have to do that for all versions, 2.8 and 2.7 is imho enough.

**Comment by tomkerkhove** [comment]
Well, if people look at certain versions below 2.7 they won't see any other providers; unless we can keep the static pages for those of course?

**Comment by JorTurFer** [comment]
Versions below 2.7/2.6 have fewer sources I think, for me 2.7 is enough as starting point

**Comment by cynthia-sg** [comment]
Hi again! 👋

  I have just created a PR (#867) for this.

I've noticed one issue while testing the changes on mobile devices. Some links were not being displayed properly in the table of contents as you can see in the screenshot below. I needed to add a new link (Authentication Providers) that wasn't going to be visible either because of this, so I've fixed it in the PR.

(this is how it looks right now)
￼
<img width="534" alt="keda_2" src="https://user-images.githubusercontent.com/1440981/182815909-ef98c7d8-326d-4a1f-b352-e2a2e4e751c8.png">


(and this is how it looks after the changes)

<img width="534" alt="Authentication Providess" src="https://user-images.githubusercontent.com/1440981/182815659-1447b1a1-4214-4e5e-b17b-1a749c7926df.png">


￼

**Comment by tomkerkhove** [comment]
Awesome, thank you!
